### ISSUE TITLE
Additional Pack sizes

### ISSUE THREAD

**Issue by mkaburu** [chap-uzima/IQCare#25]
-Abacavir/Lamivudine (ABC/3TC) 600/300mg FDC Tabs available pack size is 60. There is a new pack size of 30
Artemether/Lumefantrine 20mg/120mg Tabs available is 24s we need to add new packs of 12s and 6s for paeds

**Comment by Muchina-David** [comment]
@mkaburu ABC/3TC 600/300mg - I have confirmed the pack size is actually 30's. It appears the reporting tool (FCDRR) has an error. There is no pack of 60's. @chris-githu what can we do about this?

@mkaburu For Artemether/ Lumefantrine (anti-malarial) the 24's is the official one (for the program) because of reducing inventory size for the OI drugs. Usually what happens, an adult will get 4 tablets, the children get 3 or 2 from the same pack depending on weight. As such, facilities can only enter 24's.

**Comment by chris-githu** [comment]
@mkaburu @vogoti 
Have the two sites Kiserian and Kikuyu received ABC/3TC yet?
If not we can edit the drug packaging for that drug and correct the installation scripts going forward.

**Comment by Muchina-David** [comment]
@chris-githu For Kiserian, they don't have the drug so we did not add yesterday. For Kikuyu, the team is there right now.

**Comment by mkaburu** [comment]
@chris-githu  No they have not received any yet

**Comment by chris-githu** [comment]
@vogoti @mkaburu 
I have sent you the update script for ABC/3TC via email.
Please run and confirm.

What do we want to do about `Artemether/Lumefantrine`?

**Comment by Muchina-David** [comment]
@chris-githu For Artemether/Lumefantrine and other OI drugs in the separate OI drugs list. The pack sizes are many in the market and the program sort of puts a limit on what is dispensed.  I believe all patient age/ weight bands are catered for in the formulations and pack sizes available.

**Comment by Muchina-David** [comment]
@chris-githu On second thought, we might get a facility that does not have the 24s but has the others. So i think we can just add the other pack sizes also. I will share the details on email.

**Comment by chris-githu** [comment]
@mkaburu @vogoti 
Sent the scripts for this via email. 
Please run at the two sites and review.

**Comment by vogoti** [comment]
@chris-githu the script received is for Abacavir/Lamivudine (ABC/3TC) 600/300mg FDC Tabs,you had shared this earlier and we had already run it.
Is there another script we are supposed to run?

**Comment by mkaburu** [comment]
This is done
